### ISSUE TITLE
build break

### ISSUE THREAD

**Issue by jwinarske** [maximeborges/libmetal-rs#1]
error[E0557]: feature has been removed
 --> src/lib.rs:2:12
  |
2 | #![feature(const_fn)]
  |            ^^^^^^^^ feature has been removed
  |
  = note: split into finer-grained feature gates

**Comment by jwinarske** [comment]
changing `#![feature(const_fn)]` to `#![feature(const_mut_refs)]` and `rustup default nightly` fixes it.

**Comment by jwinarske** [comment]
You also have some clippy errors.  Easy fix

**Comment by maximeborges** [comment]
Fixed in 06eaccf8debeac32a1e7e4092318df814802d3c1
Thanks!
